baseurl = "https://mobbiao.github.io/MyBlog/"
languageCode = "zh-Hans"
paginate = 5
title = "Biao的博客"

DefaultContentLanguage = "zh-cn"

hasCJKLanguage = false

# Change it to your Disqus shortname before using
disqusShortname = "Biao"
